// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkVh4SfJAdqVYBTDVgwIF-1vMeEY-_Q1U',
    appId: '1:311567409576:web:c053feb98d093788913d9d',
    messagingSenderId: '311567409576',
    projectId: 'medicalapp-8cca9',
    authDomain: 'medicalapp-8cca9.firebaseapp.com',
    storageBucket: 'medicalapp-8cca9.firebasestorage.app',
    measurementId: 'G-7Z014JY2SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVWAn7nSX5_IYpyRNHxXrs5JO5SCx2oWU',
    appId: '1:311567409576:android:fdfbbfba9d0c92e4913d9d',
    messagingSenderId: '311567409576',
    projectId: 'medicalapp-8cca9',
    storageBucket: 'medicalapp-8cca9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdByDh-T8GuoQlhPOGDkzIxnP6p-HyzH0',
    appId: '1:311567409576:ios:1fee927a532b01ba913d9d',
    messagingSenderId: '311567409576',
    projectId: 'medicalapp-8cca9',
    storageBucket: 'medicalapp-8cca9.firebasestorage.app',
    androidClientId: '311567409576-7go3cj43b6elp8lv3o1u0l1bd1uirvm7.apps.googleusercontent.com',
    iosClientId: '311567409576-b0pqpj5jpgmafn4jlv27890u0scvvt05.apps.googleusercontent.com',
    iosBundleId: 'com.example.madPracticeOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdByDh-T8GuoQlhPOGDkzIxnP6p-HyzH0',
    appId: '1:311567409576:ios:1fee927a532b01ba913d9d',
    messagingSenderId: '311567409576',
    projectId: 'medicalapp-8cca9',
    storageBucket: 'medicalapp-8cca9.firebasestorage.app',
    androidClientId: '311567409576-7go3cj43b6elp8lv3o1u0l1bd1uirvm7.apps.googleusercontent.com',
    iosClientId: '311567409576-b0pqpj5jpgmafn4jlv27890u0scvvt05.apps.googleusercontent.com',
    iosBundleId: 'com.example.madPracticeOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkVh4SfJAdqVYBTDVgwIF-1vMeEY-_Q1U',
    appId: '1:311567409576:web:9eb2edf21033d21e913d9d',
    messagingSenderId: '311567409576',
    projectId: 'medicalapp-8cca9',
    authDomain: 'medicalapp-8cca9.firebaseapp.com',
    storageBucket: 'medicalapp-8cca9.firebasestorage.app',
    measurementId: 'G-00T349B3K8',
  );
}
